name:        brick-dropdownmenu
version:     0.1.0
github:      "mlang/brick-dropdownmenu"
license:     BSD3
author:      "Mario Lang"
maintainer:  "mlang@blind.guru"
copyright:   "2018 Mario Lang"

extra-source-files:
- ChangeLog.md

category:    Graphics
synopsis:    A drop-down menu widget for brick.
description: A simple drop-down menu widget for the declarative
  text user interface library brick.
 
  Each submenu and menu item can have an associated global key binding.

dependencies:
- base >= 4.7 && < 5
- brick >= 0.35 && < 0.42
- containers
- microlens
- microlens-ghc
- microlens-th
- pointedlist
- vector
- vty

flags:
  demo:
    description: Build the demo program
    manual: yes
    default: no

library:
  source-dirs: src

executables:
  brick-dropdownmenu-demo:
    main:                Demo.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - brick-dropdownmenu
    - text
    when:
    - condition: flag(demo)
      then:
        buildable: yes
      else:
        buildable: no
